namespace SmartHR.NET.Tests.Entities;

/// <summary>BizEstablishmentの単体テスト</summary>
public static class BizEstablishmentTest
{
    /// <summary>事業所情報APIのサンプルレスポンスJSON</summary>
    internal const string Json = "{"
    + "\"id\": \"string\","
    + "\"hel_ins_type\": \"kyokai_kenpo\","
    + "\"hel_ins_name\": \"string\","
    + "\"name\": \"string\","
    + "\"soc_ins_name\": \"string\","
    + "\"soc_ins_owner_id\": \"string\","
    + "\"soc_ins_address\": {"
    + "  \"id\": \"string\","
    + "  \"country_number\": \"string\","
    + "  \"zip_code\": \"string\","
    + "  \"pref\": \"string\","
    + "  \"city\": \"string\","
    + "  \"street\": \"string\","
    + "  \"building\": \"string\","
    + "  \"literal_yomi\": \"string\""
    + "},"
    + "\"soc_ins_tel_number\": \"string\","
    + "\"lab_ins_name\": \"string\","
    + "\"lab_ins_owner_id\": \"string\","
    + "\"lab_ins_address\": {"
    + "  \"id\": \"string\","
    + "  \"country_number\": \"string\","
    + "  \"zip_code\": \"string\","
    + "  \"pref\": \"string\","
    + "  \"city\": \"string\","
    + "  \"street\": \"string\","
    + "  \"building\": \"string\","
    + "  \"literal_yomi\": \"string\""
    + "},"
    + "\"lab_ins_tel_number\": \"string\","
    + "\"jurisdiction_tax\": \"string\","
    + "\"salary_payer_address\": {"
    + "  \"id\": \"string\","
    + "  \"country_number\": \"string\","
    + "  \"zip_code\": \"string\","
    + "  \"pref\": \"string\","
    + "  \"city\": \"string\","
    + "  \"street\": \"string\","
    + "  \"building\": \"string\","
    + "  \"literal_yomi\": \"string\""
    + "},"
    + "\"updated_at\": \"2021-10-20T00:43:00.028Z\","
    + "\"created_at\": \"2021-10-20T00:43:00.028Z\""
    + "  }";
}
