namespace SmartHR.NET.Tests.Entities;

/// <summary>Dependentの単体テスト</summary>
public static class DependentTest
{
    /// <summary>家族情報APIのサンプルレスポンスJSON</summary>
    internal const string Json = "{"
    + "  \"id\": \"string\","
    + "  \"crew_id\": \"string\","
    + "  \"relation_name\": \"string\","
    + "  \"relation\": {"
    + "    \"id\": \"string\","
    + "    \"name\": \"string\","
    + "    \"preset_type\": \"string\","
    + "    \"is_child\": true,"
    + "    \"position\": 0,"
    + "    \"created_at\": \"2021-10-19T23:42:05.697Z\","
    + "    \"updated_at\": \"2021-10-19T23:42:05.697Z\""
    + "  },"
    + "  \"is_spouse\": true,"
    + "  \"last_name\": \"string\","
    + "  \"first_name\": \"string\","
    + "  \"last_name_yomi\": \"string\","
    + "  \"first_name_yomi\": \"string\","
    + "  \"birth_at\": \"2021-10-19\","
    + "  \"moved_at\": \"2021-10-19\","
    + "  \"gender\": \"male\","
    + "  \"job\": \"string\","
    + "  \"basic_pension_number\": \"string\","
    + "  \"basic_pension_number_image\": {"
    + "    \"file_name\": \"string\","
    + "    \"url\": \"string\""
    + "  },"
    + "  \"live_together_type\": \"living_together\","
    + "  \"address\": {"
    + "    \"id\": \"string\","
    + "    \"country_number\": \"string\","
    + "    \"zip_code\": \"string\","
    + "    \"pref\": \"string\","
    + "    \"city\": \"string\","
    + "    \"street\": \"string\","
    + "    \"building\": \"string\","
    + "    \"literal_yomi\": \"string\""
    + "  },"
    + "  \"tel_number\": \"string\","
    + "  \"handicapped_type\": \"ordinary_handicapped\","
    + "  \"handicapped_note_type\": \"string\","
    + "  \"handicapped_note_delivery_at\": \"2021-10-19\","
    + "  \"handicapped_image\": {"
    + "    \"file_name\": \"string\","
    + "    \"url\": \"string\""
    + "  },"
    + "  \"remittance_to_relative\": 0,"
    + "  \"remittance_image1\": {"
    + "    \"file_name\": \"string\","
    + "    \"url\": \"string\""
    + "  },"
    + "  \"remittance_image2\": {"
    + "    \"file_name\": \"string\","
    + "    \"url\": \"string\""
    + "  },"
    + "  \"remittance_image3\": {"
    + "    \"file_name\": \"string\","
    + "    \"url\": \"string\""
    + "  },"
    + "  \"social_insurance_support_type\": \"unsupported\","
    + "  \"income\": 0,"
    + "  \"monthly_income\": 0,"
    + "  \"soc_ins_qualified_at\": \"2021-10-19\","
    + "  \"soc_ins_qualified_reason\": \"string\","
    + "  \"soc_ins_disqualified_at\": \"2021-10-19\","
    + "  \"disqualified_reason_type\": \"death\","
    + "  \"disqualified_reason\": \"string\","
    + "  \"tax_law_support_type\": \"unsupported\","
    + "  \"tax_deduction_income\": 0,"
    + "  \"tax_deduction_qualified_at\": \"2021-10-19\","
    + "  \"tax_deduction_qualified_reason\": \"string\","
    + "  \"tax_deduction_disqualified_at\": \"2021-10-19\","
    + "  \"tax_deduction_disqualified_reason_type\": \"death\","
    + "  \"tax_deduction_disqualified_reason\": \"string\","
    + "  \"maternity_handbook_image\": {"
    + "    \"file_name\": \"string\","
    + "    \"url\": \"string\""
    + "  },"
    + "  \"kinship_image\": {"
    + "    \"file_name\": \"string\","
    + "    \"url\": \"string\""
    + "  },"
    + "  \"created_at\": \"2021-10-19T23:42:05.698Z\","
    + "  \"updated_at\": \"2021-10-19T23:42:05.698Z\","
    + "  \"code\": \"string\""
    + "}";
}
