namespace SmartHR.NET.Tests.Entities;

/// <summary>Userの単体テスト</summary>
public static class UserTest
{
    /// <summary>ユーザ情報APIのサンプルレスポンスJSON</summary>
    internal const string Json = "{"
    + "  \"id\": \"string\","
    + "  \"email\": \"string\","
    + "  \"admin\": true,"
    + "  \"role\": {"
    + "    \"id\": \"string\","
    + "    \"name\": \"string\","
    + "    \"description\": \"string\","
    + "    \"crews_scope\": \"crews_scope_all\","
    + "    \"crews_scope_query\": {},"
    + "    \"session_timeout_in\": 0,"
    + "    \"preset_type\": \"string\""
    + "  },"
    + "  \"agreement_for_electronic_delivery\": true,"
    + "  \"crew_id\": \"string\","
    + "  \"tenants\": ["
    + "    {"
    + "      \"id\": \"string\","
    + "      \"name\": \"string\","
    + "      \"subdomains\": ["
    + "        {"
    + "          \"name\": \"string\","
    + "          \"active\": true"
    + "        }"
    + "      ],"
    + "      \"customer_id\": \"string\","
    + "      \"trial_start_at\": \"2021-10-20\","
    + "      \"trial_end_at\": \"2021-10-20\","
    + "      \"addon_subscribable\": true,"
    + "      \"subscribed_plan\": {"
    + "        \"name\": \"string\""
    + "      },"
    + "      \"general_setting\": {"
    + "        \"show_agreement_for_electronic_delivery_in_invitation\": true,"
    + "        \"multilingualization\": true"
    + "      },"
    + "      \"updated_at\": \"2021-10-20T00:43:00.008Z\","
    + "      \"created_at\": \"2021-10-20T00:43:00.008Z\""
    + "    }"
    + "  ],"
    + "  \"invitation_created_at\": \"2021-10-20\","
    + "  \"invitation_opened_at\": \"2021-10-20\","
    + "  \"invitation_accepted_at\": \"2021-10-20\","
    + "  \"invitation_answered_at\": \"2021-10-20\","
    + "  \"suppressed_email_logs\": ["
    + "    {"
    + "      \"id\": \"string\","
    + "      \"suppression_type\": 0,"
    + "      \"reason\": \"string\","
    + "      \"suppressed_at\": \"2021-10-20\","
    + "      \"updated_at\": \"2021-10-20T00:43:00.008Z\","
    + "      \"created_at\": \"2021-10-20T00:43:00.008Z\""
    + "    }"
    + "  ],"
    + "  \"has_password\": true,"
    + "  \"updated_at\": \"2021-10-20T00:43:00.008Z\","
    + "  \"created_at\": \"2021-10-20T00:43:00.008Z\""
    + "}";
}
